version: '3'
services:
  chronicler:
    container_name: chronicler
    environment:
      - TZ=America/Chicago
    image: balexander85/twitter-chronicler
    restart: unless-stopped
    volumes:
      - /media/bot/conf:/usr/src/twitter_chronicler/conf
      - /media/bot/logs:/usr/src/twitter_chronicler/logs
      - /media/bot/screenshots:/usr/src/twitter_chronicler/screenshots
